version: '3.8'

services:
  app:
    container_name: django-app
    build: .
    image: &app app
    restart: "no"
    command: python3 start.py --service-name database --ip database --port 3306
    env_file: &envfile
      - env.env
    ports:
      - 8000:8000
    volumes:
      - ./App:/App
    depends_on:
      - database

  database:
    container_name: database
    platform: linux/x86_64
    image: mysql:5.6
    restart: always
    env_file: *envfile
    volumes:
      - ~/.mdbdata/App:/var/lib/mysql
    ports:
      - 3306:3306
    expose:
      - 3306

  redis:
    container_name: redis
    image: redis:6.2.6
    ports:
      - 6378:6379
    volumes:
      - ~/.mdbdata/App/redisdata:/data

  celery-worker:
    container_name: celery-worker
    build: .
    image: *app
    restart: "no"
    env_file: *envfile
    command: celery --app=worker.worker.app worker --concurrency=1 --hostname=worker@%h --loglevel=INFO
    volumes:
      - ./App:/App
    depends_on:
      - rabbitmq

  celery-beat:
    container_name: celery-beat
    build: .
    image: *app
    env_file: *envfile
    command: python3 -m celery --app=worker.worker.app beat -l debug -f /var/log/App-celery-beat.log --pidfile=/tmp/celery-beat.pid
    volumes:
      - ./App:/App
    depends_on:
      - celery-worker

  flower:
    container_name: flower
    image: zoomeranalytics/flower:0.9.2-4.0.2-2
    restart: "no"
    env_file: *envfile
    ports:
      - 5555:5555
    depends_on:
      - rabbitmq

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3
    env_file: *envfile
    ports:
      - 5672:5672
